### PR TITLE
Fix: accessible-astro-components URL change

### PR DESCRIPTION
**Pull request by Lakelimbo**
Was just randomly browsing the integrations and found that they changed the URL.

### CODE REVIEW

**Review by jasikpark — APPROVED** [review]
lgtm

**Comment by tony-sull** [comment]
That build break is related to an issue with how our deploys are setup in the new codebase!  Looking into a fix with #606 that unblocks the build break when private env variables aren't defined in community PRs

**Comment by tony-sull** [comment]
That's more like it, community PRs unblocked!

**Review by tony-sull — APPROVED** [review]
thanks for catching this!  Still working on a nightly script that updates data from NPM and github 😅

**Comment by Lakelimbo** [comment]
> thanks for catching this! Still working on a nightly script that updates data from NPM and github 😅

no problem! And thank you for the fix as well! 😄

**Pull request merged**
