### PR TITLE
Add "slnt" 0 for `font-obviously` to prevent unexpected italic in safari.

### PR DESCRIPTION
**Pull request by ktym4a**
about [message from discord](https://discord.com/channels/830184174198718474/872579324446928896/1218555975234097214).

I think this will fix it, but I would like to check preview once.

### CODE REVIEW

**Review by OliverSpeir — APPROVED** [review]
Approving to see deployment

edit: I can't approve to see deployment 😅

**Comment by delucis** [comment]
Authorized the preview deploy — should be here shortly. Thanks for tackling @ktym4a!

**Comment by ktym4a** [comment]
Looks good to me in Safari on MacOS!
and I don't have IOS, so I can't check about that.

**Comment by natemoo-re** [comment]
Thank you _so_ much for the PR! You got this fixed way before we did and we should have merged it right away.

It took a bit longer, but I reworked our font handling completely in https://github.com/withastro/astro.build/pull/1031. We are now subsetting our font and have eliminated the `slnt` axis for performance reasons!

**Pull request closed without merging**
