### PR TITLE
add repl link to the new websites navbar

### PR DESCRIPTION
**Pull request by okikio**
add repl link to the new websites navbar

### CODE REVIEW

**Review by jonathantneal — APPROVED** [review]
I want @natemoo-re to glance, but +1 from me.

**Comment by Princesseuh** [comment]
This might cause an issue on mobile devices as the menu is currently only designed for a small amount of elements

**Comment by okikio** [comment]
@princesseuh I've updated the name of the link from "Playground" to "Repl", what do you think?

**Comment by Princesseuh** [comment]
I suspect that it still might be an issue on very thin phones but, there's no real solutions that isn't "implement a mobile menu" so 🤷‍♀️

I think that Playground look nicer and is more in line with other tools

**Comment by okikio** [comment]
I'll probably need to contact nate to confirm how he'd like us to approach this, without wrecking the design

**Comment by FredKSchott** [comment]
fixed the CSS to fit on mobile! +1 from me

**Pull request merged**
