### PR TITLE
Add Transloadit's logo to the Gold Sponsors list

### PR DESCRIPTION
**Pull request by nqst**
Hey Astro team,

I'm Alexander, a designer from [Transloadit](https://transloadit.com). We've been [Gold Sponsors](https://opencollective.com/transloadit) of Astro since January 2023, and we'd like to showcase our logo in your sponsor lists.

Here, I've added Transloadit's logo to [astro.build](https://astro.build), and updated the image with the sponsor logos used in the Astro repo README.

The logo has been placed alongside the existing sponsors, in line with the current styling.

## Changes

- Added Transloadit logo in the sponsors section on the website.
- Updated `public/sponsors.png` used in the [Astro repo README](https://github.com/withastro/astro).

## Preview

Screenshot 2023-08-14 at 16 26 56@2x

sponsors

If any adjustments are needed, please let me know.

### CODE REVIEW

**Comment by clearlyTHUYDOAN** [comment]
Thanks, Alexander. We'll take a look!

**Review by itsMapleLeaf — APPROVED** [review]
Needed to update the order to respect sponsor amounts. Approved!

**Comment by nqst** [comment]
Thanks for the quick turnaround!

I have a small nitpick: in https://github.com/withastro/astro.build/pull/765/commits/6ea034b765350f7cc7df684670296376e5c09d06 the dark-mode version of our logo is used (you can see it in the diff). Unfortunately, it doesn't look great on a white background. Could you please replace it with the correct version?

I'm happy to create another PR, or you can simply use an updated image below — whichever is more convenient for you.

sponsors

**Comment by itsMapleLeaf** [comment]
@nqst Ah, we missed that. Yes, if you could send in another PR for that image, that'd be great 🙌

**Pull request merged**
