### PR TITLE
Add theme astro wordpress starter

### PR DESCRIPTION
**Pull request by okikio**
### Theme title

Astro WordPress Starter

### Short description and preview image

A flexible starting point for people interested in using Astro with WordPress as a headless CMS using WPGraphQL.
Screen Shot 2022-11-28 at 3 12 59 PM

### Public repository URL

https://github.com/JEverhart383/astro-wordpress-starter

### Live demo URL

https://hnhcu867jnlofzb7xsfeuta0c.js.wpenginepowered.com/

cc @JEverhart383

### CODE REVIEW

**Comment by delucis** [comment]
Ooh, cool! I believe theme submissions are now done via the custom submissions form: https://astro.build/themes/submit/

That lets authors provide more information about their theme than we used to have. Check out https://astro.build/themes/details/astro-paper/ for example.

**Comment by delucis** [comment]
Oh wait, just realising this a PR not an issue 😴 

My bad, sorry — I’ll let @tony-sull & @itsMapleLeaf take this one in that case.

**Comment by okikio** [comment]
Great thanks 👍🏽

**Comment by tony-sull** [comment]
Just saw this *after* taking a pass closing out open theme & showcase submissions #484 😅 

Our README could really use some docs on how the nightly stats work!  One nuance here is the `pnpm update:themes` script needs to run to build the full `themes.json` list

I think that will actually fail here, the `tags` array is actually an enum list that only supports [certain values](https://github.com/withastro/astro.build/blob/1bd1d62ff6d3ceac0cf8f79548634a801e249df0/src/types.ts#L66), zod should throw an error here when updating the themes JSON

@okikio I'll close this issue out **only** because I already added this one without noticing the open PR first.  Thank you for following up on this one though!  I'll get our README updated either today or Monday with proper details on how the themes/showcase/integrations pages are setup 👍

**Pull request closed without merging**
