### PR TITLE
add @tigrisdata/astro integration

### LINKED ISSUE #653: INTEGRATION: @tigrisdata/astro
### NPM package name

@tigrisdata/astro

### Short description (if different than package.json) and icon

"Access NoSQL data from your Astro site."

LOGOMARK OCEANGREEN

### Homepage URL (if different than package.json)

https://github.com/tigrisdata/tigris-astro

### PR DESCRIPTION
**Pull request by MichaelJolley**
closes #653

### CODE REVIEW

**Comment by MichaelJolley** [comment]
Hola @tony-sull! Could you take a peek here and let me know if I've missed anything? We're announcing this integration today and would love to have it listed on the site. Also, ✅Feature Request for a new integration category for "Databases." There didn't seem to be a category that we specifically fit in. Would love your guidance there.

image

**Comment by tony-sull** [comment]
>  ✅Feature Request for a new integration category for "Databases."

That's not a category we've had much interest in yet, great to see our list of Astro integrations expanding!  I'll have to check back with other integrations to see if we have a few more database-related integrations already - search & filter is *much* more flexible in our these days so we can definitely look at adding a new "Databases" category if/when there's a few integrations that fit :+1:

**Review by tony-sull — APPROVED** [review]
Looks good to me, thanks for jumping in with a PR to update the integration details!

**Comment by tony-sull** [comment]
@MichaelJolley looks great, thanks!  I can get this merged in now unless you have any other updates you want to include 👍

**Comment by MichaelJolley** [comment]
I think we're good to go. Thanks for the help!

**Pull request merged**
