### PR TITLE
added new themes - added images with better resolution on past Lexington's featured themes…

### PR DESCRIPTION
**Pull request by michael-andreuzza**
Thank you Astro, have a great day.

### CODE REVIEW

**Comment by surjithctly** [comment]
Hey 👋

Shouldn't you be using the new **Submit a Theme** form instead? https://astro.build/themes/submit/

**Comment by michael-andreuzza** [comment]
> Hey 👋
> 
> Shouldn't you be using the new **Submit a Theme** form instead? https://astro.build/themes/submit/

Been doing like this for very long time. Is it a must?

**Comment by ElianCodes** [comment]
Hey @michael-andreuzza, don't worry. It's fine to update your themes or add them via PR!

We'll take a look at it soon enough!

**Comment by michael-andreuzza** [comment]
> Hey @michael-andreuzza, don't worry. It's fine to update your themes or add them via PR!
> 
> We'll take a look at it soon enough!

Hey Elian. 
Thank you so much, not a rush also thank you so much for getting back to me! Appreciate it :-)

**Review by tony-sull — APPROVED** [review]
These look excellent 😍 

Sorry for the delay getting this list of themes reviewed!  I'll follow up with a separate PR to set the published date for the new themes so the new ones here are all flagged as "NEW" 🚀

**Comment by michael-andreuzza** [comment]
Oh

> These look excellent 😍
> 
> Sorry for the delay getting this list of themes reviewed! I'll follow up with a separate PR to set the published date for the new themes so the new ones here are all flagged as "NEW" 🚀

Hey Tony, I completely forgot about it until Elian commented 😅, thank you so much for taking care of this, I really appreciate it!

Have a good day!

**Pull request merged**
