### PR TITLE
Update AstroWind theme

### PR DESCRIPTION
**Pull request by prototypa**
[**AstroWind**](https://github.com/onwidget/astrowind) is one of the most started and forked themes in the Astro environment. However, it has been in the Astro repository (https://astro.build/themes/details/astrowind/) for quite some time using some legacy images from the first version and without content on the theme page.

With this PR we are adding new images and content. What has been changed:

Changes to `astrowind.md`
- Update description
- Add to categories: `portafolio` and `blog`
- Add to tools: `typescript`
- Remove 1 legacy images and add 4 new images 
- Add content

Changes to `_images/`
- Remove 1 legacy image and add 4 new images

PD: Thanks for the excellent work this fabulous framework

### CODE REVIEW

**Comment by ElianCodes** [comment]
Hey @prototypa! You should be able to access and update your themes here: https://portal.astro.build, in case you encounter any problems, please let me know!

**Comment by prototypa** [comment]
Hi @ElianCodes 

Thanks for the reply. I've been trying but it won't let me. **AstroWind** was one of the first templates to be published in the _Astro_ environment and belongs to my organization. I publish everything through my **onWidget** organization and I do not have access to it from the portal.

Screenshot 2024-03-13 at 10 12 47 AM

What are you suggesting? I would like **AstroWind** to remain part of **onWidget**, not make a new instance in my name.

Thanks

**Comment by prototypa** [comment]
Hi @ElianCodes 

I was reviewing other templates that do the same thing I want, for example the case of Astrosaas: https://astro.build/themes/details/astrosaas/

The template is displayed in the name of _lexingtonthemes_, however in `content/themes/astrosaas.md` the author metadata is different, it is in the name of _michael-andreuzza_:

https://github.com/withastro/astro.build/blob/main/src/content/themes/astrosaas.md?plain=1#L13C10-L13C27

I guess you guys must have a database that makes those relationships.

Please, if you could do something like this for me too. I have almost ready 5 more themes with the same **AstroWind** quality and I would like them to come out under the name of **onWidget**.

Thank you

**Comment by ElianCodes** [comment]
Hey @prototypa ! The md files are not in use anymore and are deprecated. I can do the same thing for you as I did for Michael (Lexington Themes) and change your account into the onWidget org. Do you want me to do that?

**Comment by prototypa** [comment]
Oh yes please, if you can change my account to use onWidget that would be perfect. Thanks

**Comment by ElianCodes** [comment]
@prototypa, you should be able to access your theme now!

**Comment by prototypa** [comment]
Super! Thank you. Good day

**Pull request closed without merging**
