### PR TITLE
astro v0.23 release post

### PR DESCRIPTION
**Pull request by FredKSchott**
@natemoo-re what are our chances of updating astro.build to use Astro v0.23 (`next` or `latest`) before this blog post goes out? This post seems to really be pushing its code blocks past their breaking point for syntax highlighting, and I'd really like to use Shiki if I can: https://docs.astro.build/en/guides/markdown-content/#syntax-highlighting (support added in v0.23.0-next.2, I believe).

### CODE REVIEW

**Comment by tony-sull** [comment]
@FredKSchott I just filed [PR #28](https://github.com/withastro/astro.build/pull/28) upgrading astro.build to `astro@next` :+1:

**Comment by FredKSchott** [comment]
That fixed the code blocks! Nice!

**Review by tony-sull — APPROVED** [review]
Looks good to me! I double checked the preview as well, didn't see any issues with the 0.23 update or move to Shiki so we should be all set there

I'm good to see this merged in once the release is out :+1:

**Review by natemoo-re — APPROVED** [review]
This looks great!

**Pull request merged**
