### PR TITLE
Use correct Transloadit's logo in sponsors.png

### PR DESCRIPTION
**Pull request by nqst**
## Changes

Replacing the incorrect Transloadit's logo with the correct one on the sponsors image — as agreed in https://github.com/withastro/astro.build/pull/765 :)

### CODE REVIEW

**Comment by tony-sull** [comment]
Looks like the correct icon was swapped in before merging #765 🚀

**Comment by delucis** [comment]
Sorry about that @nqst! We’ll take a look soon.

**Comment by itsMapleLeaf** [comment]
Sorry again about the slowness on this. It looks like there's a conflict on the edited image. If you could update that for us again, I'll have this merged in right away 🏎️

**Comment by nqst** [comment]
> Sorry again about the slowness on this. It looks like there's a conflict on the edited image. If you could update that for us again, I'll have this merged in right away 🏎️

Thanks! I've just updated the image and resolved the conflict — now it should be good to go 🚀

**Pull request merged**
