### PR TITLE
improve `@analogjs/astro-angular` integration home page link

### PR DESCRIPTION
**Pull request by apatel369**
This pull request updates the link for the `@analogjs/astro-angular` integration on the Astro Integrations page. 
The previous link directed users to the AnalogJS homepage, which did not provide specific information about the Astro Angular integration. By updating the link to point directly to the `@analogjs/astro-angular` documentation, users can now easily find detailed information and instructions on how to use the integration, improving the overall user experience. 

I have tested this PR on at least three of the following browsers:

- [ ] Chrome / Chromium
- [ ] Firefox
- [ ] Android Firefox
- [ ] Safari
- [ ] iOS Safari

### CODE REVIEW

**Comment by pascal-brand38** [comment]
Looks good to me 👍

Can you also update ```scripts/integrations.json``` with
```
"@analogjs/astro-angular": {
	"homepageUrl": "https://analogjs.org/docs/packages/astro-angular/overview"
},
```

It prevents the old url to come back on nightly build when ```npm run update:integrations -- --unsafe``` is ran

**Review by delucis — COMMENTED** [review]
Thanks for this @apatel369 and for the helpful review @pascal-brand38! I’ll also note that maybe the _most_ ideal place to improve this would be at the source: https://github.com/analogjs/analog/blob/c08d1c1f4bb4e5d4c615bbba35426ed6940dae00/packages/astro-angular/package.json#L25

That way the more helpful link would be available on npm etc. as well.

**Comment by apatel369** [comment]
> Looks good to me 👍
> 
> Can you also update `scripts/integrations.json` with
> 
> ```
> "@analogjs/astro-angular": {
> 	"homepageUrl": "https://analogjs.org/docs/packages/astro-angular/overview"
> },
> ```
> 
> It prevents the old url to come back on nightly build when `npm run update:integrations -- --unsafe` is ran

Thanks. I wasn't aware of this at all. I have merged your PR.

**Comment by apatel369** [comment]
> Thanks for this @apatel369 and for the helpful review @pascal-brand38! I’ll also note that maybe the _most_ ideal place to improve this would be at the source: https://github.com/analogjs/analog/blob/c08d1c1f4bb4e5d4c615bbba35426ed6940dae00/packages/astro-angular/package.json#L25
> 
> That way the more helpful link would be available on npm etc. as well.

Great suggestion. I will create a PR there as well.

**Review by delucis — APPROVED** [review]
Perfect. Thanks again @apatel369 and @pascal-brand38 🙌

**Pull request merged**
