### PR TITLE
Update Houston images

### PR DESCRIPTION
**Pull request by natemoo-re**

### CODE REVIEW

**Comment by jasikpark** [comment]
Can `@astrojs/image` be used to generate Webp images w/ the pngs?

**Comment by jasikpark** [comment]
image
oh, i guess they could all be webp?

**Comment by natemoo-re** [comment]
Ehh I don't know enough about our image setup. I leave that to @tony-sull! But I think we are just hard-coding `png` for consistency right now.

**Comment by tony-sull** [comment]
Yep, we're pre-rendering `webp` images for now **but** will be switching to the new core image APIs as soon as possible!

**Comment by doodlemarks** [comment]
thank you @natemoo-re!

**Pull request merged**
