### PR TITLE
upgrade biome

### PR DESCRIPTION
**Pull request by itsMapleLeaf**
biome doesn't error on top-level return in `.astro` files now! 🎉

### CODE REVIEW

**Comment by itsMapleLeaf** [comment]
* **#1063** <a href="https://app.graphite.dev/github/pr/withastro/astro.build/1063?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @itsMapleLeaf and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ElianCodes — APPROVED** [review]

**Comment by itsMapleLeaf** [comment]
oh sorry, this isn't finished and should be a draft 😅

**Comment by ElianCodes** [comment]
hehe yeah, I saw the lint job not passing and the conflicts 👁️

**Comment by itsMapleLeaf** [comment]
superceded by #1073

**Pull request closed without merging**
