### PR TITLE
Updated details on Aubergine Theme and added new theme: Dusk

### PR DESCRIPTION
**Pull request by michael-andreuzza**

### CODE REVIEW

**Comment by tony-sull** [comment]
@michael-andreuzza Thanks for keeping this theme descriptions up-to-date!

Looks like I don't have permissions to checkout the PR branch, would you mind reverting changes to the `.vscode` directory to make sure our settings aren't lost?

**Comment by michael-andreuzza** [comment]
> @michael-andreuzza Thanks for keeping this theme descriptions up-to-date!
> 
> Looks like I don't have permissions to checkout the PR branch, would you mind reverting changes to the `.vscode` directory to make sure our settings aren't lost?

I was getting errors with the .vscode file...
Will revert!

**Comment by tony-sull** [comment]
> I was getting errors with the .vscode file...
Will revert!

Oh interesting!  That's definitely a bug we can look into on our end, our VS Code config shouldn't break community contributions!

**Comment by michael-andreuzza** [comment]
> > I was getting errors with the .vscode file...
> > Will revert!
> 
> Oh interesting! That's definitely a bug we can look into on our end, our VS Code config shouldn't break community contributions!

Should we remove this pr and I redo everything to see if it happens again?

**Comment by tony-sull** [comment]
@michael-andreuzza sorry for the delay here while I've been catching up after a long weekend!  I'll get these merged in today and figure out why the linter is complaining, our config is a little heavy handed sometimes

For the VS Code config issue you hit, if you still hit it when running our repo locally would you mind opening an [issue](https://github.com/withastro/astro.build/issues) for us to track?  I'm not sure what might be going on there yet but that's definitely worth us looking into

**Comment by michael-andreuzza** [comment]
> @michael-andreuzza sorry for the delay here while I've been catching up after a long weekend! I'll get these merged in today and figure out why the linter is complaining, our config is a little heavy handed sometimes
> 
> For the VS Code config issue you hit, if you still hit it when running our repo locally would you mind opening an [issue](https://github.com/withastro/astro.build/issues) for us to track? I'm not sure what might be going on there yet but that's definitely worth us looking into

I missed this  sorry Tony. Thank you so much for the help.
I will try it today, I have some new themes to add.

Again,  thank you so much.

**Pull request merged**
