### PR TITLE
adds trivago to companies

### PR DESCRIPTION
**Pull request by boehs**
https://tech.trivago.com

see https://deploy-preview-15--astro-build.netlify.app

also makes it easy to modify companies in the future!

### CODE REVIEW

**Comment by boehs** [comment]
> Hotel Trivago, image

There we go, was confused on the first comment

**Comment by okikio** [comment]
> > Hotel Trivago, image
> 
> There we go, was confused on the first comment

Lol

**Review by jonathantneal — CHANGES_REQUESTED** [review]
I would want permission before merging this. I love that people are using Astro, tho!

**Comment by FredKSchott** [comment]
Nice! This is a great logo to add. I'll merge and then maybe clean up a bit (we might need to replace an existing logo instead of adding a new one)

**Pull request merged**
