### PR TITLE
Add showcase screenshot grid to “What’s New in Astro” blog posts

### PR DESCRIPTION
**Pull request by delucis**
Adds a new `<ShowcaseGrid>` component that can be used in the “What’s New in Astro” blog post series to show a grid of links showing a screenshot of the site with information on focus/hover like we do in our existing showcase section. For example:

A page heading for Websites followed by a three-column grid of screenshots

### Usage

```mdx
{/* src/content/blog/example.mdx */}

import ShowcaseGrid from './_whats-new-components/ShowcaseGrid.astro';

export const sites = [
  { title: 'Example Site', url: 'https://example.com' },
  { title: 'Another Demo', url: 'https://demo.dev' },
];

<ShowcaseGrid items={sites} />
```

### Notes

- I’ve updated all the preceding editions of the What’s New in Astro posts to use this component too: [October](https://astro-build-git-chris-month-in-astro-showc-d6d5f7-astrodotbuild.vercel.app/blog/whats-new-october-2023/#showcase), [November](https://astro-build-git-chris-month-in-astro-showc-d6d5f7-astrodotbuild.vercel.app/blog/whats-new-november-2023/#showcase), [December](https://astro-build-git-chris-month-in-astro-showc-d6d5f7-astrodotbuild.vercel.app/blog/whats-new-december-2023/#websites)

- The card design is lifted from our existing showcase card design. This includes a title and shows the URL below that, so doesn’t entirely match our `example.com by @username` pattern that was in use in the bullet-point version. To be quick, I’ve made the title for those sites the username. In the future, we might want to use the actual site title instead.

- For speed, this uses the [11ty screenshot service](https://www.11ty.dev/docs/services/screenshots/) to generate the site screenshots and optimises those by allowing that service as a remote image source for Astro assets. In the future, we might want to add something like https://github.com/withastro/astro.build/blob/main/scripts/update-showcase.mjs to generate the screenshots instead of relying on the remote service.

### CODE REVIEW

**Comment by sarah11918** [comment]
This looks great on Desktop! Going to check on my phone now.

What would you think about something more visual to separate the Starlight in the Wild section? It sort of blends in.

**Comment by delucis** [comment]
> What would you think about something more visual to separate the Starlight in the Wild section? It sort of blends in.

Good question! Do you mean to make the two grids more different or literally just some kind of more visual separation before the heading? Could definitely be fun to have some more designed elements in these repeated formats, like a `<StarlightHeading>` with more space and a pretty background or something.

**Comment by sarah11918** [comment]
I think just literally more visual separation! As you said, Starlight in the wild heading maybe incorporates the Starlight logo or something?

**Comment by sarah11918** [comment]
Especially with so many sites being dark mode, and the size of the images being larger, the text heading really doesn't stand out much

image

**Review by sarah11918 — APPROVED** [review]
Approoooooving! We can consider a snazzier Starlight visual separately!

**Comment by delucis** [comment]
I guess I should leave this to @ElianCodes to merge/accept!

**Review by ElianCodes — APPROVED** [review]

**Pull request merged**
