### PR TITLE
remove duplicate showcase entry

### PR DESCRIPTION
**Pull request by sarah11918**
Someone had added their website twice, once as a netlify.app and once under their own domain.

This removes the duplicate!

### CODE REVIEW

**Comment by sarah11918** [comment]
Previewed both this month's blog post and the Showcase page and this seems fine to me!

**Review by delucis — CHANGES_REQUESTED** [review]
We should probably also add the removed domain to the blocklist in our `update-showcase` script I think? Otherwise the site will be scraped again in the future.

LMK if you need me to take care of that!

**Comment by sarah11918** [comment]
@delucis That would be helpful, yes! If you don't get to it today, I can do it later this evening.

**Review by delucis — APPROVED** [review]
Done. Should be good to go!

**Pull request merged**
