### PR TITLE
Calckey -> Firefish

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
Calckey rebranded as Firefish a few months ago, which included a new domain and logo!

### CODE REVIEW

**Review by natemoo-re — APPROVED** [review]
Thanks for opening a PR! LGTM!

**Comment by ThatOneCalculator** [comment]
Ty! I didn't optimize the webp images (just exported from screenshots), not sure if that's handled by CI, `astro:assets`, or if I have to do any optimization manually.

**Comment by ThatOneCalculator** [comment]
From the CI/CD preview deployment, seems it's not being optimized ^^;

image

**Comment by natemoo-re** [comment]
Ah that's right @ThatOneCalculator. Would be awesome if you could optimize these

**Comment by ThatOneCalculator** [comment]
Any recommended tools, or is anything fine?

**Comment by ThatOneCalculator** [comment]
14.9kb for 1x and 41.8kb for 2x now!

**Comment by ThatOneCalculator** [comment]
@natemoo-re anything else I'm missing?

**Pull request merged**
