### PR TITLE
Reorder BaseHead to prioritize order

### PR DESCRIPTION
**Pull request by jasikpark**
image

Gotta have that streamlined head 👨‍🦲 

I'm not sure this catches everything that https://github.com/rviscomi/capo.js flagged, but it should improve the order?

### CODE REVIEW

**Comment by jasikpark** [comment]
Not sure where the double title is coming from 😬

**Comment by delucis** [comment]
Nice! Do you want to share a before/after of the capo.js runs?

**Comment by jasikpark** [comment]
Before:

Screenshot 2023-06-27 at 10 42 14 AM

After:

image

**Comment by jasikpark** [comment]
I'm using the chrome extension https://chrome.google.com/webstore/detail/capo-get-your-%3Chead%3E-in-o/ohabpnaccigjhkkebjofhpmebofgpbeb which simplifies testing this

**Review by natemoo-re — APPROVED** [review]
This looks great, thanks for tackling!

**Pull request merged**
