### PR TITLE
Improve analytics script greatly

### PR DESCRIPTION
**Pull request by boehs**
this change is important because tracking people is a total *jam*

### CODE REVIEW

**Comment by matthewp** [comment]
Hah, this is fun. I would worry that it violates copyright though :/

**Comment by boehs** [comment]
I'm not well versed in law but would de minims apply? Perhaps it is excessive to have the whole song, what if it was shortened to 10 seconds?

**Comment by okikio** [comment]
Hotel Trivago, 
image

**Comment by FredKSchott** [comment]
This is really funny :) I think we're going to avoid playing an mp3 for now, but thanks for the contribution :D

**Pull request closed without merging**
